# Generated by Django 2.1.5 on 2020-02-29 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 17, 47, 16, 38754), verbose_name='date published'),
        ),
    ]
